CREATE TABLE estudiantes (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  descripcion MEDIUMTEXT NOT NULL,
  nota1 DOUBLE NOT NULL,
  nota2 DOUBLE NOT NULL,
  nota3 DOUBLE NOT NULL,
  nota_final DOUBLE NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE);
